development:
  adapter: redis
  url: <%= ENV.fetch('CABLE_REDIS_URL', 'redis://localhost:6379/2') %>
  channel_prefix: robotrack_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch('CABLE_REDIS_URL', ENV.fetch('REDIS_URL', 'redis://localhost:6379/1')) %>
  channel_prefix: robotrack_production
